services:
  postgres_container:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: monitoring
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring-net

  backend:
    build:
      context: ./backend
    environment:
      - POSTGRES_URL=postgres://postgres:postgrespassword@postgres_container:5432?sslmode=disable
    ports:
      - "8082:8082"
    depends_on:
      - postgres_container
    networks:
      - monitoring-net

  frontend:
    build:
      context: ./frontend
      args:
        ORIGIN: http://localhost:8081
        BACKEND_URL: http://backend:8082
    ports:
      - "8081:3000"
    depends_on:
      - backend
    networks:
      - monitoring-net

  pinger:
    build:
      context: ./pinger
    environment:
      - BACKEND_URL=http://backend:8082
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_RAW
    depends_on:
      - backend
    networks:
      - monitoring-net

networks:
  monitoring-net:

volumes:
  postgres_data:
