services:
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: monitoring
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring-net

#   backend:
#     build: ./backend
#     environment:
#       POSTGRES_HOST: postgres
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: monitoring
#     ports:
#       - "8080:8080"
#     depends_on:
#       - postgres
#     networks:
#       - monitoring-net

#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend
#     networks:
#       - monitoring-net

#   pinger:
#     build: ./pinger
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     depends_on:
#       - backend
#     networks:
#       - monitoring-net

networks:
  monitoring-net:

volumes:
  postgres_data:
